# Eureka Client Configuration
eureka.client.serviceUrl.defaultZone=http://dan-eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true

# Service name for discovery
spring.application.name=reservas-svc
server.port=8080
eureka.instance.instance-id=${spring.application.name}:${server.port}:${HOSTNAME:${spring.application.name}}
springdoc.swagger-ui.url=/reservas/v3/api-docs
springdoc.swagger-ui.config-url=/reservas/v3/api-docs/swagger-config