spring.application.name=reservas-svc

# ── MongoDB (local) ────────────────────────────────────────────────
spring.data.mongodb.uri=mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:rootpwd}@localhost:27017/${MONGO_DB:reservas}?authSource=admin

# ── RabbitMQ (local) ──────────────────────────────────────────────
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}

# ── Actuator ───────────────────────────────────────────────────────
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
