spring.application.name=reservas-svc

# ── MongoDB ────────────────────────────────────────────────────────
spring.data.mongodb.uri=mongodb://${MONGO_USER:root}:${MONGO_PASSWORD:rootpwd}@${MONGO_HOST:mongodb}:27017/${MONGO_DB:reservas}?authSource=admin

# ── RabbitMQ ───────────────────────────────────────────────────────
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.port=5672
spring.rabbitmq.username=${RABBITMQ_USER:admin}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:admin}
spring.amqp.deserialization.trust.all=true

# ── Actuator ───────────────────────────────────────────────────────
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=when-authorized
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=@project.version@

# ── Logging base ───────────────────────────────────────────────────
logging.level.edu.utn.frsf.isi.dan.reservas_svc=INFO
