package edu.utn.frsf.isi.dan.gestion.model;

public enum Amenity {
    PILETA,SAUNA, GIMNASIO, RESTAURANTE, BAR, ESTACIONAMIENTO, WIFI, AIRE_ACONDICIONADO, CALENTADOR, TV_CABLE, SERVICIO_HABITACIONES, LIMPIEZA_DIARIA, PISCINA_CUBIERTA, PISCINA_DESCUBIERTA, SPA, SALA_JUEGOS, SALA_REUNIONES, TRANSPORTE_AEROPUERTO
}
